# Generated by Django 2.0.13 on 2019-02-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(max_length=300),
        ),
    ]
