# Generated by Django 2.0.13 on 2019-02-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20190226_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.CharField(max_length=300),
        ),
    ]
